### ISSUE TITLE
Doesn't work as intended with MediaInfo.NET

### ISSUE THREAD

**Issue by iG8R** [magicxor/WinSyncScroll#3]
Hi.
The title speaks for itself.

https://github.com/user-attachments/assets/810ea9a1-5a7f-488a-9fac-9744fc42d327

https://github.com/stax76/MediaInfo.NET

**Comment by magicxor** [comment]
Hi @iG8R 

1) What version of Windows are you using?
2) Are you logging in directly or via RDP?
3) Have you tried turning on "[scroll inactive windows](https://www.elevenforum.com/t/turn-on-or-off-scroll-inactive-windows-in-windows-11.6102/)"?
4) Have you tried [Legacy mode](https://github.com/magicxor/WinSyncScroll?tab=readme-ov-file#legacy-mode)?

**Comment by iG8R** [comment]
Hi, @magicxor 
1. Microsoft Windows [Version 10.0.19045.2673]
2. Directly
3. This option is turned on by default.
4. Yes, in legacy mode it doesn't work at all.

**Comment by iG8R** [comment]
It feels like WSS doesn't "pass" all scroll parameters to the `to` window.
Is there any debug mode to see what is happening?

**Comment by iG8R** [comment]
Right now I checked the operation of WSS with all other windows (VScode, VS2012, Notepad++, Firefox, Chrome, Edge), it turned out that all of them have the same behavior as in the screencast in the first message.

**Comment by magicxor** [comment]
> It feels like WSS doesn't "pass" all scroll parameters to the `to` window. Is there any debug mode to see what is happening?

in `nlog.config` you may check that `minlevel` = `"Trace"`

```xml
<logger ruleName="AllToFile" name="*" minlevel="Trace" writeTo="logfile">
    <filters defaultAction="Log">
        <when condition="starts-with(logger,'System.') and level &lt; LogLevel.Warn" action="Ignore" />
        <when condition="starts-with(logger,'Microsoft.') and level &lt; LogLevel.Warn" action="Ignore" />
    </filters>
</logger>
```

then you may check `\logs\Log.current.txt`

Also, the issue may be related to coordinate conversion, scaling, or the number of displays. How many displays do you have in your system?

**Comment by iG8R** [comment]
> Also, the issue may be related to coordinate conversion, scaling, or the number of displays. How many displays do you have in your system?

2 monitors, the main one, on which I tried to use WSS, is 4K with 150% scaling, and the secondary one is FullHD with 100% scaling.

**Comment by iG8R** [comment]
[Log.current.zip](https://github.com/user-attachments/files/23537575/Log.current.zip)

**Comment by magicxor** [comment]
> 2 monitors, the main one, on which I tried to use WSS, is 4K with 150% scaling, and the secondary one is FullHD with 100% scaling.

Thank you for providing the log file. I've reviewed it, but there are no obvious issues.

To help us isolate the problem, could you please try running a test with only one monitor connected?

**Comment by iG8R** [comment]
I made 2 versions:
1. "soft" - I "disconnected" the second monitor via `Win+P` and selecting `PC screen only`.
2. "hard" - I physically disconnected the second monitor.

[Log.current.zip](https://github.com/user-attachments/files/23539125/Log.current.zip)

**Comment by magicxor** [comment]
Thanks. Did the scrolling work on any of these attempts?

**Comment by iG8R** [comment]
Unfortunately, no. Still the same as in the first post.

**Comment by magicxor** [comment]
I have another theory we could investigate. It's possible the issue is related to [UIPI](https://en.wikipedia.org/wiki/User_Interface_Privilege_Isolation).

If you have a moment, could you please try running WSS as an Administrator?

It would be very helpful if you could test this in both configurations:

- Running as Administrator with Legacy Mode disabled.
- Running as Administrator with Legacy Mode enabled.

Please let me know if either of those combinations makes any difference. Thanks!

**Comment by iG8R** [comment]
Unfortunately, the results are still the same:
1. Running as Administrator with Legacy Mode disabled - still the "to" window is jerking and stalling like in the video earlier.
2. Running as Administrator with Legacy Mode enabled - the "to" window doesn't  react at all.

**Comment by iG8R** [comment]
I still found an application that works with WSS without problems - just plain MediaInfo. (https://mediaarea.net/en/MediaInfo)
All other apps I mentioned earlier still don't work properly.

https://github.com/user-attachments/assets/2fa9b051-9e6f-41c4-9965-a43584117660

**Comment by magicxor** [comment]
Currently, the application sends all three inputs (Move to Target, Scroll, Move back to Source) as a single batch. My hypothesis is that Windows might be processing the final "Move back to Source" command before the target window has fully registered the "Scroll" command at the target coordinates.

I've created an experimental build that changes this logic. Instead of sending one large array of commands, it now sends three separate, sequential SendInput calls:

1. Move cursor to target
2. Send scroll command
3. Move cursor back to source

The hope is that this forces Windows to process each step in the correct order.

```diff
diff --git a/WinSyncScroll/ViewModels/MainViewModel.cs b/WinSyncScroll/ViewModels/MainViewModel.cs
index d424946..61b3414 100644
--- a/WinSyncScroll/ViewModels/MainViewModel.cs
+++ b/WinSyncScroll/ViewModels/MainViewModel.cs
@@ -323,14 +323,27 @@ public sealed partial class MainViewModel : IDisposable
                     var inputScrollTarget = CreateScrollInput(buffer.MouseMessageId, targetAbsoluteX, targetAbsoluteY, delta);
                     var inputMoveToSource = CreateMoveInput(sourceAbsoluteX, sourceAbsoluteY);
 
-                    var inputs = new[] { inputMoveToTarget, inputScrollTarget, inputMoveToSource };
-
                     _mouseHook.SetPreventRealScrollEvents();
 
                     if (!_options.Value.IsLegacyModeEnabled)
                     {
-                        LogSendInput(inputs);
-                        PInvoke.SendInput(inputs.AsSpan(), SizeOfInput);
+                        // Send events sequentially to ensure proper timing and processing order
+                        // This prevents the cursor from moving back to source before the scroll event is processed
+                        
+                        // Step 1: Move cursor to target window
+                        var moveToTargetArray = new[] { inputMoveToTarget };
+                        LogSendInput(moveToTargetArray);
+                        PInvoke.SendInput(moveToTargetArray.AsSpan(), SizeOfInput);
+                        
+                        // Step 2: Send scroll event at target location
+                        var scrollArray = new[] { inputScrollTarget };
+                        LogSendInput(scrollArray);
+                        PInvoke.SendInput(scrollArray.AsSpan(), SizeOfInput);
+                        
+                        // Step 3: Move cursor back to source window
+                        var moveToSourceArray = new[] { inputMoveToSource };
+                        LogSendInput(moveToSourceArray);
+                        PInvoke.SendInput(moveToSourceArray.AsSpan(), SizeOfInput);
                     }
                     else
                     {
```

Would you be willing to test this experimental build?

[1.4.0-rc.1-experimental.fix1.zip](https://github.com/user-attachments/files/23560449/1.4.0-rc.1-experimental.fix1.zip)

**Comment by iG8R** [comment]
Of course, I'm willing:)
Unfortunately, it didn't work. But I noticed one pattern - if I scroll slowly, the associated window does not respond at all, but if I scroll very quickly, some scrolling is somehow transmitted to it, as seen in the screencast.

https://github.com/user-attachments/assets/0df7c757-d242-40a1-81a0-463eb7bdc898

**Comment by magicxor** [comment]
I've just released a new version, **v1.4.0-rc.5** (https://github.com/magicxor/WinSyncScroll/releases/tag/1.4.0-rc.5).

This version includes a significant fix for **Legacy Mode**. (It now uses `PostMessage` instead of `SendMessage` and ensures the coordinates are correct for the `WM_MOUSEWHEEL` message).

Could you please download this new version, enable Legacy Mode, and test if the scrolling now works correctly for you?

---

### If it still doesn't work:

I've included a new diagnostic tool in the release assets named `VisualTestUtil`. This will help us test WSS.

If the fix above doesn't work, could you please try this:
1.  Run `VisualTestUtil` **twice** (so you have two test windows open).
2.  In WinSyncScroll, select one test window as the **"From"** target.
3.  Select the second test window as the **"To"** target.
4.  Try scrolling in the "From" window.

Could you please make a screen recording of this test (using those two test windows) so I can see what's happening?

Here is a screencast showing how this test looks on my machine (with and without Legacy Mode) so you can compare the expected behavior.

https://github.com/user-attachments/assets/58cfd8e1-1b37-4770-a4d0-4fa2f6d25195

https://github.com/user-attachments/assets/531a9381-8a03-4be8-803f-0142aea2bfc2

---

One last question, as I'm exploring all possibilities: **What model of mouse are you using?** I'm just wondering if there might be any special manufacturer software or drivers (like Logitech Options, Razer Synapse, etc.) installed that could be intercepting or altering the mouse messages.

Thanks!

**Comment by iG8R** [comment]
Ooh... Cool!:)
Unfortunately, WSS still doesn't work with all the windows I mentioned earlier, but it works perfectly with your test windows.

https://github.com/user-attachments/assets/e51785cc-5bde-4e87-9728-348003cccccf

https://github.com/user-attachments/assets/1b74e141-2fa8-4e54-b5de-db0e9c0eed52

Regarding my mouse(s):
1. The first and main one is Swiftpoint Z1 https://www.swiftpoint.eu/products/gaming-mice-swiftpoint-z2
2. The second one is Roccat Leadr https://www.tweaktown.com/reviews/8323/roccat-leadr-wireless-rgb-gaming-mouse-review/index.html

**Comment by magicxor** [comment]
Thank you so much for the detailed testing, the videos, and the info on your mice.

Honestly, I'm not sure what else to suggest right now to fix this on your PC. I will definitely post back in this thread if I come up with any new ideas.

I did some more testing, and on my machine, WSS works correctly with VSCode, Notepad++, Firefox, Chrome, and Edge. However, I just discovered that I have the exact same bug as you when I try to sync with Visual Studio 2026: Legacy mode doesn't work at all, and normal mode only registers large/fast scrolls.

This is actually good news, as it finally gives me a reliable way to reproduce the problem. I'll use Visual Studio as my main test case to debug this further as soon as I get some time.

**Comment by iG8R** [comment]
@magicxor 
Thank you very much for your efforts!
